#!/bin/bash
#exit  antix bash backend
. /usr/local/lib/desktop-session/desktop-session-file-locations.sh

declare -A OPTION
OPTION[1]='-l | l | --logout'
OPTION[2]='-L | L | --lock'
OPTION[3]='-H | H | --hibernate'
OPTION[4]='-s | s | --shutdown'
OPTION[5]='-S | S | --suspend'
OPTION[6]='-r | r | --reboot'
OPTION[7]='-R | R | --restart'
OPTION[8]='-h | h | --help'
OPTION[9]='any key'

declare -A TXT
TXT[1]='Logout of the current session'
TXT[2]='Lock the current session'
TXT[3]='Set the machine into hibernate'
TXT[4]='Shutdown your machine'
TXT[5]='Set the machine into suspend'
TXT[6]='Reboot your machine'
TXT[7]='Restart the session'
TXT[8]='help'
TXT[9]='script exit'

tui() {
	GREEN='\033[32m'
	BLUE='\033[01;34m'
	YELLOW='\e[1;33m'
	LCYAN='\033[1;36m'
	NORMAL='\e[0m'

	echo ''

	#A1="${YELLOW}${TXT[1]}${NORMAL}	${OPTION[1]}"
	#A2="${YELLOW}${TXT[2]}${NORMAL}		${OPTION[2]}"
	#A3="${YELLOW}${TXT[3]}${NORMAL}	${OPTION[3]}"
	#A4="${YELLOW}${TXT[4]}${NORMAL}		${OPTION[4]}"
	#A5="${YELLOW}${TXT[5]}${NORMAL}		${OPTION[5]}"
	#A6="${YELLOW}${TXT[6]}${NORMAL}			${OPTION[6]}"
	#A7="${YELLOW}${TXT[7]}${NORMAL}			${OPTION[7]}"
	#A8="${YELLOW}${TXT[8]${NORMAL}					${OPTION[8]}"
	#A9="${YELLOW}${TXT[9]${NORMAL}				any key"

	#ARR=("$A1" "$A2" "$A3" "$A4" "$A5" "$A6" "$A7" "$A8" "$A9")
	
	list=()

	#echo ""
	#echo "${#TXT[@]}"
	#echo ""
	
#exit
		
#потом fzf править
	if command -v fzf >/dev/null 2>&1 ; then
		echo "Select the desired option:"
		#CHOICE=$(printf "%b\n" "${ARR[@]}" | awk '{print NR ": " $0}' | fzf --ansi --height 40% --reverse --cycle)
		
		#CHOICE=$(printf "%b %-31b %b\n" "${LCYAN}$((i + 1)).${NORMAL}" "${YELLOW}${OPTION[$((i + 1))]}${NORMAL}" "${LCYAN}${TXT[$((i + 1))]}${NORMAL}" | awk '{print NR ": " $0}' | fzf --ansi --height 40% --reverse --cycle)
		
			#Флаг --height в fzf задает высоту окна выбора, которое отображается в терминале. Когда вы указываете --height 40%, это означает, что высота окна fzf будет составлять 40% от высоты терминала, в котором вы его запускаете.
			#Пример использования:

				#Если ваш терминал имеет высоту 100 строк, то fzf --height 40% создаст окно высотой 40 строк.
				#Это позволяет вам контролировать, сколько места в терминале будет занимать интерфейс fzf, что может быть полезно, если вы хотите оставить место для других команд или вывода.

			#Другие варианты:

			#Вы также можете указать высоту в абсолютных значениях, например:

				#--height 20 — высота окна будет 20 строк.
				#--height 50% — высота окна будет 50% от высоты терминала.


		#for ((i=0; i<${#TXT[@]}; i++)); do
			#list+=("${LCYAN}$((i + 1)).${NORMAL} ${YELLOW}${OPTION[$i]}${NORMAL} ${LCYAN}${TXT[$i]}${NORMAL}")
		#done
		
		for ((i=1; i<=${#TXT[@]}; i++)); do
			formatted_line=$(printf "%b %-31b %b\n" "${LCYAN}$((i)).${NORMAL}" "${YELLOW}${OPTION[$i]}${NORMAL}" "${LCYAN}${TXT[$i]}${NORMAL}")
			list+=("$formatted_line")
		done

		CHOICE=$(printf "%b\n" "${list[@]}" | fzf --ansi --reverse --cycle)
		#CHOICE=$(printf "%s" "${list[@]}" | fzf)
		
		CHOICE=$(echo "$CHOICE" | cut -c 1)

	else
		for i in "${!ARR[@]}"; do
			#echo -e "$((i + 1)). ${ARR[i]}"
			printf "%b %-31b %b\n" "${LCYAN}$((i + 1)).${NORMAL}" "${YELLOW}${OPTION[$((i + 1))]}${NORMAL}" "${LCYAN}${TXT[$((i + 1))]}${NORMAL}"

		done
		echo ''
		echo -e "${GREEN}Enter number, short option or long option (For example: 1 | -l | l | --logout):${NORMAL} "
		read CHOICE
	fi
	
	main
	}
	
help() {
    echo "Usage:"
	printf "%-30s %s\n" "${OPTION[1]}" "${TXT[1]}"
	printf "%-30s %s\n" "${OPTION[2]}" "${TXT[2]}"
	printf "%-30s %s\n" "${OPTION[3]}" "${TXT[3]}"
	printf "%-30s %s\n" "${OPTION[4]}" "${TXT[4]}"
	printf "%-30s %s\n" "${OPTION[5]}" "${TXT[5]}"
	printf "%-30s %s\n" "${OPTION[6]}" "${TXT[6]}"
	printf "%-30s %s\n" "${OPTION[7]}" "${TXT[7]}"
	printf "%-30s %s\n" "${OPTION[8]}" "${TXT[8]}"
    }
    
main() {
	if [[ $CHOICE  -eq 0 ]]; then
		CHOICE="$ARG"
	fi

	case $CHOICE in
		1 | -l | --logout)
			$desktop_session_logout
			;;
		2 | -L | --lock)
			xlock
			;;
		3 | -H |--hibernate)
		    sudo pm-hibernate
		    ;;
		4 | -s | --shutdown)
			if [ -e /etc/live/config/save-persist -o -e /live/config/persist-save.conf ] && which persist-config &> /dev/null; then
				sudo persist-config --shutdown --command poweroff
			else
				sync
				#sudo chvt 1#this causes exit to reappear on halt
				sudo poweroff
			fi
			;;
		5 | -S | --suspend)
			sudo pm-suspend
			;;
		6 | -r | --reboot)
			if [ -e /etc/live/config/save-persist -o -e /live/config/persist-save.conf ] && which persist-config &> /dev/null; then
				sudo persist-config --shutdown --command reboot
			else
				sync
				#sudo chvt 1#this causes exit to reappear on reboot
				sudo reboot
			fi
			;;
		7 | -R | --Restart)
			$desktop_session_restart
			;;
		8 | -h | --help)
			help
			;;
		9)
			exit
			;;
		-t | --tui)
			tui
			return
			;;
		*)
			if [ "$DISPLAY" ]; then
				$desktop_session_exit_gui &
				exit
			else
				echo "$1 Not an option"
				help;
			fi
			;;
	esac
	}

ARG="$1"
CHOICE=0
main
