#!/bin/bash
#exit  antix bash backend
. /usr/local/lib/desktop-session/desktop-session-file-locations.sh

tui() {
	GREEN='\033[32m'
	YELLOW='\033[33m'
	LCYAN='\033[1;36m'
	NORMAL='\e[0m'

	echo ''

	A1="${LCYAN}1${NORMAL}. ${YELLOW}Logout of the current session${NORMAL}	-l | l | --logout"
	A2="${LCYAN}2${NORMAL}. ${YELLOW}Lock the current session${NORMAL}		-L | L | --lock"
	A3="${LCYAN}3${NORMAL}. ${YELLOW}Set the machine into hibernate${NORMAL}	-H | H | --hibernate"
	A4="${LCYAN}4${NORMAL}. ${YELLOW}Shutdown your machine${NORMAL}		-s | s | --shutdown"
	A5="${LCYAN}5${NORMAL}. ${YELLOW}Set the machine into suspend${NORMAL}		-S | S | --suspend"
	A6="${LCYAN}6${NORMAL}. ${YELLOW}Reboot your machine${NORMAL}			-r | r | --reboot"
	A7="${LCYAN}7${NORMAL}. ${YELLOW}Restart the session${NORMAL}			-R | R | --restart"
	A8="${LCYAN}8${NORMAL}. ${YELLOW}script exit${NORMAL}				any key"

	ARR=("$A1" "$A2" "$A3" "$A4" "$A5" "$A6" "$A7" "$A8")

	if command -v fzf >/dev/null 2>&1 ; then
		echo "Select the desired option:"
		CHOICE=$(printf "%b\n" "${ARR[@]}" | fzf --ansi --height 40% --reverse --cycle)
		CHOICE=$(echo "$CHOICE" | cut -c 1)

	else
		for i in "${!ARR[@]}"; do
			echo -e "${ARR[i]}"
		done
		echo ''
		echo -e "${GREEN}Enter number, short option or long option (For example: 1 | -l | l | --logout):${NORMAL} "
		read CHOICE
	fi
	
	main
	}
	
help() {
    echo "Usage:"
    echo "-l | --logout     Logout of the current session";
    echo "-L | --lock       Lock the current session";
    echo "-H | --hibernate  Set the machine into hibernate";
    echo "-s | --shutdown   Shutdown your machine";
    echo "-S | --suspend    Set the machine into suspend";
    echo "-r | --reboot     Reboot your machine";
    echo "-R | --restart    Restart the session";
    }
    
main() {
	if [[ $CHOICE  -eq 0 ]]; then
		CHOICE="$ARG"
	fi

	case $CHOICE in
		1 | -l | --logout)
			$desktop_session_logout
			;;
		2 | -L | --lock)
			xlock
			;;
		3 | -H |--hibernate)
		    sudo pm-hibernate
		    ;;
		4 | -s | --shutdown)
			if [ -e /etc/live/config/save-persist -o -e /live/config/persist-save.conf ] && which persist-config &> /dev/null; then
				sudo persist-config --shutdown --command poweroff
			else
				sync
				#sudo chvt 1#this causes exit to reappear on halt
				sudo poweroff
			fi
			;;
		5 | -S | --suspend)
			sudo pm-suspend
			;;
		6 | -r | --reboot)
			if [ -e /etc/live/config/save-persist -o -e /live/config/persist-save.conf ] && which persist-config &> /dev/null; then
				sudo persist-config --shutdown --command reboot
			else
				sync
				#sudo chvt 1#this causes exit to reappear on reboot
				sudo reboot
			fi
			;;
		7 | -R | --Restart)
			$desktop_session_restart
			;;
		8)
			exit
			;;
		-h | --help)
			help
			;;
		-t | --tui)
			tui
			return
			;;
		*)
			if [ "$DISPLAY" ]; then
				$desktop_session_exit_gui &
				exit
			else
				echo "$1 Not an option"
				help;
			fi
			;;
	esac
	}

ARG="$1"
CHOICE=0
main
