#!/bin/bash
#exit  antix bash backend
. /usr/local/lib/desktop-session/desktop-session-file-locations.sh

tui() {
	GREEN='\033[32m'
	YELLOW='\033[33m'
	LCYAN='\033[1;36m'
	NORMAL='\e[0m'

	echo ''
	
	OPTION_1="-l | l | --logout"
	OPTION_2="-L | L | --lock"
	OPTION_3="-H | H | --hibernate"
	OPTION_4="-s | s | --shutdown"
	OPTION_5="-S | S | --suspend"
	OPTION_6="-r | r | --reboot"
	OPTION_7="-R | R | --restart"
	OPTION_8="-h | h | --help"
	

	A1="${LCYAN}1${NORMAL}. ${YELLOW}Logout of the current session${NORMAL}	${OPTION_1}"
	A2="${LCYAN}2${NORMAL}. ${YELLOW}Lock the current session${NORMAL}		${OPTION_2}"
	A3="${LCYAN}3${NORMAL}. ${YELLOW}Set the machine into hibernate${NORMAL}	${OPTION_3}"
	A4="${LCYAN}4${NORMAL}. ${YELLOW}Shutdown your machine${NORMAL}		${OPTION_4}"
	A5="${LCYAN}5${NORMAL}. ${YELLOW}Set the machine into suspend${NORMAL}		${OPTION_5}"
	A6="${LCYAN}6${NORMAL}. ${YELLOW}Reboot your machine${NORMAL}			${OPTION_6}"
	A7="${LCYAN}7${NORMAL}. ${YELLOW}Restart the session${NORMAL}			${OPTION_7}"
	A8="${LCYAN}8${NORMAL}. ${YELLOW}help${NORMAL}					${OPTION_8}"
	A9="${LCYAN}9${NORMAL}. ${YELLOW}script exit${NORMAL}				any key"

	ARR=("$A1" "$A2" "$A3" "$A4" "$A5" "$A6" "$A7" "$A8" "$A9")

	if command -v fzf >/dev/null 2>&1 ; then
		echo "Select the desired option:"
		CHOICE=$(printf "%b\n" "${ARR[@]}" | fzf --ansi --height 40% --reverse --cycle)
		CHOICE=$(echo "$CHOICE" | cut -c 1)

	else
		for i in "${!ARR[@]}"; do
			echo -e "${ARR[i]}"
		done
		echo ''
		echo -e "${GREEN}Enter number, short option or long option (For example: 1 | -l | l | --logout):${NORMAL} "
		read CHOICE
	fi
	
	main
	}
	
help() {
    echo "Usage:"
    echo "${OPTION_1}     Logout of the current session";
    echo "${OPTION_2}       Lock the current session";
    echo "${OPTION_3}  Set the machine into hibernate";
    echo "${OPTION_4}   Shutdown your machine";
    echo "${OPTION_5}    Set the machine into suspend";
    echo "${OPTION_6}     Reboot your machine";
    echo "${OPTION_7}    Restart the session";
    echo "${OPTION_8}       help";
    }
    
main() {
	if [[ $CHOICE  -eq 0 ]]; then
		CHOICE="$ARG"
	fi

	case $CHOICE in
		1 | -l | --logout)
			$desktop_session_logout
			;;
		2 | -L | --lock)
			xlock
			;;
		3 | -H |--hibernate)
		    sudo pm-hibernate
		    ;;
		4 | -s | --shutdown)
			if [ -e /etc/live/config/save-persist -o -e /live/config/persist-save.conf ] && which persist-config &> /dev/null; then
				sudo persist-config --shutdown --command poweroff
			else
				sync
				#sudo chvt 1#this causes exit to reappear on halt
				sudo poweroff
			fi
			;;
		5 | -S | --suspend)
			sudo pm-suspend
			;;
		6 | -r | --reboot)
			if [ -e /etc/live/config/save-persist -o -e /live/config/persist-save.conf ] && which persist-config &> /dev/null; then
				sudo persist-config --shutdown --command reboot
			else
				sync
				#sudo chvt 1#this causes exit to reappear on reboot
				sudo reboot
			fi
			;;
		7 | -R | --Restart)
			$desktop_session_restart
			;;
		8 | -h | --help)
			help
			;;
		9)
			exit
			;;
		-t | --tui)
			tui
			return
			;;
		*)
			if [ "$DISPLAY" ]; then
				$desktop_session_exit_gui &
				exit
			else
				echo "$1 Not an option"
				help;
			fi
			;;
	esac
	}

ARG="$1"
CHOICE=0
main
